version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ttutor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: UFvPDJudQbuYCp6mAiXwzjN7Mqf6hgby
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ttutor
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: UFvPDJudQbuYCp6mAiXwzjN7Mqf6hgby

volumes:
  pgdata:
