version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=ttutor
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=VYKP9QjBo472QFz
    ports:
      - "6543:5432"

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=VYKP9QjBo472QFz
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ttutor
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=VYKP9QjBo472QFz
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"

