@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class item {
   data: jsonb
   date_created: timestamp(6) with time zone
   history_action: varchar(255)
   internal_id: bigint
   item_type: varchar(255)
   last_updated: timestamp(6) with time zone
   status: varchar(255)
   iteration_id: bigint
   project_id: bigint
   id: bigint
}
class iteration {
   date_created: timestamp(6) with time zone
   iteration_commit_sha: varchar(255)
   last_updated: timestamp(6) with time zone
   semantic_id: varchar(255)
   project_id: bigint
   id: bigint
}
class level {
   color: varchar(255)
   name: varchar(255)
   project_id: bigint
   id: bigint
}
class project {
   date_created: timestamp(6) with time zone
   last_code_fetched: timestamp(6) with time zone
   last_opened: timestamp(6) with time zone
   last_updated: timestamp(6) with time zone
   name: varchar(255)
   repo_name: varchar(255)
   repo_url: varchar(255)
   owner_id: bigint
   id: bigint
}
class relationship {
   date_created: timestamp(6) with time zone
   description: varchar(255)
   history_action: varchar(255)
   last_updated: timestamp(6) with time zone
   type: varchar(255)
   end_item_id: bigint
   iteration_id: bigint
   start_item_id: bigint
   id: bigint
}
class user {
   avatar_url: varchar(255)
   date_created: timestamp(6) with time zone
   email: varchar(255)
   github_id: bigint
   github_login: varchar(255)
   last_updated: timestamp(6) with time zone
   name: varchar(255)
   password: varchar(255)
   provider: varchar(255)
   provider_id: varchar(255)
   role: varchar(255)
   username: varchar(255)
   id: bigint
}
class user_secret {
   secret_type: varchar(255)
   secret_value: varchar(255)
   user_id: bigint
   id: bigint
}
class user_secret_project {
   project_id: bigint
   user_secret_id: bigint
}

item                 -[#595959,plain]-^  iteration           : "iteration_id:id"
item                 -[#595959,plain]-^  project             : "project_id:id"
iteration            -[#595959,plain]-^  project             : "project_id:id"
level                -[#595959,plain]-^  project             : "project_id:id"
project              -[#595959,plain]-^  user                : "owner_id:id"
relationship         -[#595959,plain]-^  item                : "end_item_id:id"
relationship         -[#595959,plain]-^  item                : "start_item_id:id"
relationship         -[#595959,plain]-^  iteration           : "iteration_id:id"
user_secret          -[#595959,plain]-^  user                : "user_id:id"
user_secret_project  -[#595959,plain]-^  project             : "project_id:id"
user_secret_project  -[#595959,plain]-^  user_secret         : "user_secret_id:id"
@enduml
