#!/bin/sh

# Credits: http://stackoverflow.com/a/750191

git filter-branch -f --env-filter "
    GIT_AUTHOR_NAME='Havriil Pietukhin'
    GIT_AUTHOR_EMAIL='pietukhin1@uniba.sk'
    GIT_COMMITTER_NAME='Havriil Pietukhin'
    GIT_COMMITTER_EMAIL='pietukhin1@uniba.sk'
  " HEAD