/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * traceability-tutor
 */
import type { ApiFieldError } from './apiFieldError';

export interface ApiErrorResponse {
  code?: string;
  fieldErrors?: ApiFieldError[];
  message?: string;
  status?: number;
}
