/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * traceability-tutor
 */

export enum HistoryAction {
  CREATE= 'CREATE',
  UPDATE= 'UPDATE',
  DELETE= 'DELETE',
  NO_CHANGES= 'NO_CHANGES',

}