/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProjectDTO {
  dateCreated?: Date;
  id?: number;
  lastModified?: Date;
  lastOpened?: Date;
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  owner: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  repoUrl: string;
}
