/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * traceability-tutor
 */

export interface UserDTO {
  /**
   * @minLength 0
   * @maxLength 255
   */
  email?: string;
  id?: number;
  name?: string;
  role?: string;
  username?: string;
}
